from pathlib import Path

ROOT_DIR   = Path(__file__).resolve().parent

DATA_DIR   = ROOT_DIR / "data"
NSYNTH_DIR = DATA_DIR  / "nsynth"
NSYNTH_PREPROCESSED_DIR = DATA_DIR / "nsynth-preprocessed"

DDSP_DIR = ROOT_DIR / "ddsp"
NOTEBOOK_DIR = ROOT_DIR / "notebooks"

EXPERIMENTS_DIR = ROOT_DIR / "experiments"
EXPERIMENTS_RESULTS = EXPERIMENTS_DIR / "results"
EXPERIMENTS_AUDIO = EXPERIMENTS_RESULTS / "audio"
EXPERIMENTS_AUDIO_GENETIC = EXPERIMENTS_AUDIO / "genetic"
EXPERIMENTS_AUDIO_GRADIENT = EXPERIMENTS_AUDIO / "gradient"
EXPERIMENTS_AUDIO_TARGET = EXPERIMENTS_AUDIO / "target"
EXPERIMENTS_RESULTS_TABLES = EXPERIMENTS_RESULTS / "tables"